name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions: {} # Each job defines its own permissions explicitly

jobs:
  build:
    name: Build
    permissions:
      contents: read # Access to check out code and install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Env
        run: env

      - name: Check installed chromium
        run: |
          ls -R /usr/local/share/chromium

      - name: Get Playwright Version
        id: get-playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(
            pnpm exec playwright --version \
              | sed "s/Version //"
          )
          echo "PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          key: playwright-${{ steps.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
          path: |
            ~/.cache/ms-playwright

      - name: Test
        run: |
          pnpm exec playwright install --with-deps chromium
          pnpm run test

      - name: What has playwright installed?
        run: |
          ls -R ~/.cache/ms-playwright
